// Defines the various access roles available to workspace users.
export const USER_ROLES = {
  WORKSPACE_ADMIN: 'WORKSPACE_ADMIN',
  WORKSPACE_MANAGER: 'WORKSPACE_MANAGER',
  TECH_LEAD: 'TECH_LEAD',
  SENIOR_ENGINEER: 'SENIOR_ENGINEER',
  SOFTWARE_ENGINEER: 'SOFTWARE_ENGINEER',
  PROJECT_MEMBER: 'PROJECT_MEMBER',
  RESTRICTED: 'RESTRICTED',
  INTERN: 'INTERN',
};

// Lists all specific action permissions applicable within the application.
export const PERMISSIONS = {
  INVITE_USERS: 'INVITE_USERS',
  VIEW_PORTFOLIO: 'VIEW_PORTFOLIO',
  CREATE_PROJECT: 'CREATE_PROJECT',
  EDIT_PROJECT: 'EDIT_PROJECT',
  ASSIGN_TASKS: 'ASSIGN_TASKS',
  CREATE_TASKS: 'CREATE_TASKS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MANAGE_BILLING: 'MANAGE_BILLING',
  USE_MAGIC_BAR: 'USE_MAGIC_BAR',
  MANAGE_ROLES: 'MANAGE_ROLES',
};

// Maps each user role to its allowed set of functional permissions.
export const ROLE_PERMISSIONS = {
  [USER_ROLES.WORKSPACE_ADMIN]: ['*'],
  [USER_ROLES.WORKSPACE_MANAGER]: [
    PERMISSIONS.INVITE_USERS,
    PERMISSIONS.VIEW_PORTFOLIO,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.USE_MAGIC_BAR,
  ],
  [USER_ROLES.TECH_LEAD]: [
    PERMISSIONS.VIEW_PORTFOLIO,
    PERMISSIONS.EDIT_PROJECT,
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.USE_MAGIC_BAR,
  ],
  [USER_ROLES.SENIOR_ENGINEER]: [
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CREATE_TASKS,
    PERMISSIONS.USE_MAGIC_BAR,
  ],
  [USER_ROLES.SOFTWARE_ENGINEER]: [
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CREATE_TASKS,
  ],
  [USER_ROLES.PROJECT_MEMBER]: [
    PERMISSIONS.ASSIGN_TASKS,
    PERMISSIONS.CREATE_TASKS,
  ],
  [USER_ROLES.INTERN]: [PERMISSIONS.CREATE_TASKS],
  [USER_ROLES.RESTRICTED]: [],
};
