// Defines the path strings and route generation functions for application navigation.
export const ROUTES = {
  DASHBOARD: '/',
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id) => `/project/${id}`,
  MY_TASKS: '/my-tasks',
  TASK_DETAIL: (id) => `/task/${id}`,
  TEAMS: '/teams',
  SETTINGS: '/settings',
  COMMAND_CENTER: '/cto-dashboard',
  EXECUTION_COMMANDER: '/execution-commander',
  TEAM_COMMAND_CENTER: '/team-command-center',
  SYSTEM_HEALTH_CONTROL: '/system-health-control',
  EXECUTION_CONTROL: '/execution-control',
  PERSONAL_WORK_CONSOLE: '/work-console',
  GUIDED_WORK_ASSISTANT: '/guided-assistant',
  LEARNING_WORKSPACE: '/learning-workspace',
  QUALITY_CONTROL: '/quality-control',
  QUALITY_STRATEGY: '/quality-strategy',
  QUALITY_COMMAND: '/quality-command',
  HR: '/hr',
  ADMIN_PANEL: '/admin/dashboard',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  PRICING: '/pricing',
  BILLING: '/admin/billing',
};
